"""
Fortune Templates Package
오늘의 운세를 위한 템플릿 모듈

8개 영역: 총운, 학업운, 재물운, 연애운, 결혼운, 직업운, 사업운, 건강운
"""

from .overall import *
from .study import *
from .wealth import *
from .love import *
from .marriage import *
from .career import *
from .business import *
from .health import *
from .common import *

__all__ = [
    # Overall (총운)
    'OVERALL_EXCELLENT', 'OVERALL_GOOD', 'OVERALL_AVERAGE', 'OVERALL_CAUTION', 'OVERALL_DIFFICULT',
    'UNSEONG_ENERGY', 'SPECIAL_HARMONY', 'SPECIAL_CONFLICT', 'SPECIAL_PUNISHMENT',
    'SEASON_MOOD', 'WEEKDAY_SPECIAL',
    
    # Study (학업운)
    'STUDY_EXCELLENT', 'STUDY_GOOD', 'STUDY_AVERAGE', 'STUDY_CAUTION', 'STUDY_DIFFICULT',
    'STUDY_BY_SIBSUNG', 'STUDY_SITUATION',
    
    # Wealth (재물운)
    'WEALTH_EXCELLENT', 'WEALTH_GOOD', 'WEALTH_AVERAGE', 'WEALTH_CAUTION', 'WEALTH_DIFFICULT',
    'WEALTH_BY_SIBSUNG', 'WEALTH_SITUATION',
    
    # Love (연애운)
    'LOVE_SINGLE_EXCELLENT', 'LOVE_SINGLE_GOOD', 'LOVE_SINGLE_AVERAGE', 'LOVE_SINGLE_CAUTION', 'LOVE_SINGLE_DIFFICULT',
    'LOVE_COUPLE_EXCELLENT', 'LOVE_COUPLE_GOOD', 'LOVE_COUPLE_AVERAGE', 'LOVE_COUPLE_CAUTION', 'LOVE_COUPLE_DIFFICULT',
    'LOVE_BY_SIBSUNG',
    
    # Marriage (결혼운)
    'MARRIAGE_SINGLE_EXCELLENT', 'MARRIAGE_SINGLE_GOOD', 'MARRIAGE_SINGLE_AVERAGE', 'MARRIAGE_SINGLE_CAUTION', 'MARRIAGE_SINGLE_DIFFICULT',
    'MARRIAGE_MARRIED_EXCELLENT', 'MARRIAGE_MARRIED_GOOD', 'MARRIAGE_MARRIED_AVERAGE', 'MARRIAGE_MARRIED_CAUTION', 'MARRIAGE_MARRIED_DIFFICULT',
    'MARRIAGE_BY_SIBSUNG',
    
    # Career (직업운)
    'CAREER_EXCELLENT', 'CAREER_GOOD', 'CAREER_AVERAGE', 'CAREER_CAUTION', 'CAREER_DIFFICULT',
    'CAREER_BY_SIBSUNG', 'CAREER_SITUATION',
    
    # Business (사업운)
    'BUSINESS_EXCELLENT', 'BUSINESS_GOOD', 'BUSINESS_AVERAGE', 'BUSINESS_CAUTION', 'BUSINESS_DIFFICULT',
    'BUSINESS_BY_SIBSUNG', 'BUSINESS_SITUATION',
    
    # Health (건강운)
    'HEALTH_EXCELLENT', 'HEALTH_GOOD', 'HEALTH_AVERAGE', 'HEALTH_CAUTION', 'HEALTH_DIFFICULT',
    'HEALTH_BY_ELEMENT', 'HEALTH_BY_UNSEONG', 'HEALTH_BY_SEASON', 'HEALTH_BY_AGE', 'HEALTH_SPECIAL',
    
    # Common (공통)
    'GREETINGS', 'CLOSINGS', 'LUCKY_COLORS', 'LUCKY_NUMBERS', 'LUCKY_DIRECTIONS',
    'LUCKY_FOODS', 'LUCKY_ACTIVITIES', 'TIME_ADVICE', 'WEEKDAY_TRAITS', 'MONTHLY_TRAITS'
]
